//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrosHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int StockId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<decimal> DeliveryChanrge { get; set; }
        public Nullable<decimal> DiscountedPrice { get; set; }
        public Nullable<decimal> ToTalPrice { get; set; }
        public string BrandName { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Amount { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
